;;; dax-mode.el --- major mode for editing DAX code. -*- coding: utf-8; lexical-binding: t; -*-

;; Copyright © 2019, by fpvmorais@gmail.com

;; Author: Pedro Morais ( fpvmorais@gmail.com )
;; Version: 1.0
;; Created: 2017 10 16
;; Keywords: languages
;; Homepage: TODO: github repo

;; This file is not part of GNU Emacs.

;;; License:

;; You can redistribute this program and/or modify it under the terms of the GNU General Public License version 2.

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.dax\\'" . dax-mode))

(defun dax-pretty-print ()
  "Pretty print the DAX buffer via DaxFormatter API."
  (interactive)
  (goto-char (point-min))
  (while (search-forward ";" nil t)
    (replace-match ","))
  (goto-char (point-min))
  (let* (
         (url-request-method "POST")
         (url-request-extra-headers '(("Content-Type" . "application/json")))
         (url-request-data (json-encode `(("Dax" ., (delete-and-extract-region (point-min) (point-max)) ))))
         (buf (current-buffer))
         (newbuff (url-retrieve-synchronously "http://www.daxformatter.com/api/daxformatter/DaxFormat/"))
         )
    (set-buffer newbuff)
    (goto-char (point-min))
    (re-search-forward "^$")
    (delete-region (point) (point-min))
    (setq noQuotes (buffer-string))
    (setq noRN (replace-regexp-in-string "\\\\r\\\\n" "
" noQuotes))
    (setq noBars (replace-regexp-in-string "\\\\" "" noRN))
    (setq noCRs (replace-regexp-in-string "" "" noBars))
    (princ noCRs buf)
    (kill-buffer newbuff)
    )
  )

;; each category of keyword is given a particular face
(setq dax-font-lock-keywords
      (let* (
             ;; define several category of keywords
             (x-keywords '("VAR" "RETURN" "EVALUATE" "DEFINE"))
	     (x-types '("Binary"
			"Boolean"
			"Currency"
			"DateTime"
			"Decimal"
			"Integer"
			"String"
			"Variant"))
					;(x-constants '("ACTIVE" "AGENT" "ALL_SIDES" "ATTACH_BACK"))
					;(x-events '("at_rot_target" "at_target" "attach"))
             (x-functions '("ABS"
			    "ACCRINT"
			    "ACCRINTM"
			    "ACOS"
			    "ACOSH"
			    "ACOT"
			    "ACOTH"
			    "ADDCOLUMNS"
			    "ADDMISSINGITEMS"
			    "ALL"
			    "ALLCROSSFILTERED"
			    "ALLEXCEPT"
			    "ALLNOBLANKROW"
			    "ALLSELECTED"
			    "AMORDEGRC"
			    "AMORLINC"
			    "AND"
			    "APPROXIMATEDISTINCTCOUNT"
			    "ASIN"
			    "ASINH"
			    "ATAN"
			    "ATANH"
			    "AVERAGE"
			    "AVERAGEA"
			    "AVERAGEX"
			    "BETA.DIST"
			    "BETA.INV"
			    "BITAND"
			    "BITLSHIFT"
			    "BITOR"
			    "BITRSHIFT"
			    "BITXOR"
			    "BLANK"
			    "CALCULATE"
			    "CALCULATETABLE"
			    "CALENDAR"
			    "CALENDARAUTO"
			    "CEILING"
			    "CHISQ.DIST"
			    "CHISQ.DIST.RT"
			    "CHISQ.INV"
			    "CHISQ.INV.RT"
			    "CLOSINGBALANCEMONTH"
			    "CLOSINGBALANCEQUARTER"
			    "CLOSINGBALANCEYEAR"
			    "COALESCE"
			    "COLLAPSE"
			    "COLLAPSEALL"
			    "COLUMNSTATISTICS"
			    "COMBIN"
			    "COMBINA"
			    "COMBINEVALUES"
			    "CONCATENATE"
			    "CONCATENATEX"
			    "CONFIDENCE.NORM"
			    "CONFIDENCE.T"
			    "CONTAINS"
			    "CONTAINSROW"
			    "CONTAINSSTRING"
			    "CONTAINSSTRINGEXACT"
			    "CONVERT"
			    "COS"
			    "COSH"
			    "COT"
			    "COTH"
			    "COUNT"
			    "COUNTA"
			    "COUNTAX"
			    "COUNTBLANK"
			    "COUNTROWS"
			    "COUNTX"
			    "COUPDAYBS"
			    "COUPDAYS"
			    "COUPDAYSNC"
			    "COUPNCD"
			    "COUPNUM"
			    "COUPPCD"
			    "CROSSFILTER"
			    "CROSSJOIN"
			    "CUMIPMT"
			    "CUMPRINC"
			    "CURRENCY"
			    "CURRENTGROUP"
			    "CUSTOMDATA"
			    "DATATABLE"
			    "DATE"
			    "DATEADD"
			    "DATEDIFF"
			    "DATESBETWEEN"
			    "DATESINPERIOD"
			    "DATESMTD"
			    "DATESQTD"
			    "DATESYTD"
			    "DATEVALUE"
			    "DAY"
			    "DB"
			    "DDB"
			    "DEGREES"
			    "DETAILROWS"
			    "DISC"
			    "DISTINCT"
			    "DISTINCTCOUNT"
			    "DISTINCTCOUNTNOBLANK"
			    "DIVIDE"
			    "DOLLARDE"
			    "DOLLARFR"
			    "DURATION"
			    "EARLIER"
			    "EARLIEST"
			    "EDATE"
			    "EFFECT"
			    "ENDOFMONTH"
			    "ENDOFQUARTER"
			    "ENDOFYEAR"
			    "EOMONTH"
			    "ERROR"
			    "EVALUATEANDLOG"
			    "EVEN"
			    "EXACT"
			    "EXCEPT"
			    "EXP"
			    "EXPAND"
			    "EXPANDALL"
			    "EXPON.DIST"
			    "EXTERNALMEASURE"
			    "FACT"
			    "FALSE"
			    "FILTER"
			    "FILTERS"
			    "FIND"
			    "FIRST"
			    "FIRSTDATE"
			    "FIRSTNONBLANK"
			    "FIRSTNONBLANKVALUE"
			    "FIXED"
			    "FLOOR"
			    "FORMAT"
			    "FV"
			    "GCD"
			    "GENERATE"
			    "GENERATEALL"
			    "GENERATESERIES"
			    "GEOMEAN"
			    "GEOMEANX"
			    "GROUPBY"
			    "HASH"
			    "HASONEFILTER"
			    "HASONEVALUE"
			    "HOUR"
			    "IF"
			    "IF.EAGER"
			    "IFERROR"
			    "IGNORE"
			    "INDEX"
			    "INFO.ALTERNATEOFDEFINITIONS"
			    "INFO.ANNOTATIONS"
			    "INFO.ATTRIBUTEHIERARCHIES"
			    "INFO.ATTRIBUTEHIERARCHYSTORAGES"
			    "INFO.CALCDEPENDENCY"
			    "INFO.CALCULATIONGROUPS"
			    "INFO.CALCULATIONITEMS"
			    "INFO.CATALOGS"
			    "INFO.CHANGEDPROPERTIES"
			    "INFO.COLUMNPARTITIONSTORAGES"
			    "INFO.COLUMNPERMISSIONS"
			    "INFO.COLUMNS"
			    "INFO.COLUMNSTORAGES"
			    "INFO.CULTURES"
			    "INFO.DATACOVERAGEDEFINITIONS"
			    "INFO.DATASOURCES"
			    "INFO.DELTATABLEMETADATASTORAGES"
			    "INFO.DETAILROWSDEFINITIONS"
			    "INFO.DICTIONARYSTORAGES"
			    "INFO.EXCLUDEDARTIFACTS"
			    "INFO.EXPRESSIONS"
			    "INFO.EXTENDEDPROPERTIES"
			    "INFO.FORMATSTRINGDEFINITIONS"
			    "INFO.FUNCTIONS"
			    "INFO.GENERALSEGMENTMAPSEGMENTMETADATASTORAGES"
			    "INFO.GROUPBYCOLUMNS"
			    "INFO.HIERARCHIES"
			    "INFO.HIERARCHYSTORAGES"
			    "INFO.KPIS"
			    "INFO.LEVELS"
			    "INFO.LINGUISTICMETADATA"
			    "INFO.MEASURES"
			    "INFO.MODEL"
			    "INFO.OBJECTTRANSLATIONS"
			    "INFO.PARQUETFILESTORAGES"
			    "INFO.PARTITIONS"
			    "INFO.PARTITIONSTORAGES"
			    "INFO.PERSPECTIVECOLUMNS"
			    "INFO.PERSPECTIVEHIERARCHIES"
			    "INFO.PERSPECTIVEMEASURES"
			    "INFO.PERSPECTIVES"
			    "INFO.PERSPECTIVETABLES"
			    "INFO.PROPERTIES"
			    "INFO.QUERYGROUPS"
			    "INFO.REFRESHPOLICIES"
			    "INFO.RELATEDCOLUMNDETAILS"
			    "INFO.RELATIONSHIPINDEXSTORAGES"
			    "INFO.RELATIONSHIPS"
			    "INFO.RELATIONSHIPSTORAGES"
			    "INFO.ROLEMEMBERSHIPS"
			    "INFO.ROLES"
			    "INFO.SEGMENTMAPSTORAGES"
			    "INFO.SEGMENTSTORAGES"
			    "INFO.STORAGEFILES"
			    "INFO.STORAGEFOLDERS"
			    "INFO.STORAGETABLECOLUMNS"
			    "INFO.STORAGETABLECOLUMNSEGMENTS"
			    "INFO.STORAGETABLES"
			    "INFO.TABLEPERMISSIONS"
			    "INFO.TABLES"
			    "INFO.TABLESTORAGES"
			    "INFO.VARIATIONS"
			    "INT"
			    "INTERSECT"
			    "INTRATE"
			    "IPMT"
			    "ISAFTER"
			    "ISATLEVEL"
			    "ISBLANK"
			    "ISCROSSFILTERED"
			    "ISEMPTY"
			    "ISERROR"
			    "ISEVEN"
			    "ISFILTERED"
			    "ISINSCOPE"
			    "ISLOGICAL"
			    "ISNONTEXT"
			    "ISNUMBER"
			    "ISO.CEILING"
			    "ISODD"
			    "ISONORAFTER"
			    "ISPMT"
			    "ISSELECTEDMEASURE"
			    "ISSUBTOTAL"
			    "ISTEXT"
			    "KEEPFILTERS"
			    "KEYWORDMATCH"
			    "LAST"
			    "LASTDATE"
			    "LASTNONBLANK"
			    "LASTNONBLANKVALUE"
			    "LCM"
			    "LEFT"
			    "LEN"
			    "LINEST"
			    "LINESTX"
			    "LN"
			    "LOG"
			    "LOG10"
			    "LOOKUP"
			    "LOOKUPVALUE"
			    "LOWER"
			    "MATCHBY"
			    "MAX"
			    "MAXA"
			    "MAXX"
			    "MDURATION"
			    "MEDIAN"
			    "MEDIANX"
			    "MID"
			    "MIN"
			    "MINA"
			    "MINUTE"
			    "MINX"
			    "MOD"
			    "MONTH"
			    "MOVINGAVERAGE"
			    "MROUND"
			    "NAMEOF"
			    "NATURALINNERJOIN"
			    "NATURALLEFTOUTERJOIN"
			    "NETWORKDAYS"
			    "NEXT"
			    "NEXTDAY"
			    "NEXTMONTH"
			    "NEXTQUARTER"
			    "NEXTYEAR"
			    "NOMINAL"
			    "NONVISUAL"
			    "NORM.DIST"
			    "NORM.INV"
			    "NORM.S.DIST"
			    "NORM.S.INV"
			    "NOT"
			    "NOW"
			    "NPER"
			    "ODD"
			    "ODDFPRICE"
			    "ODDFYIELD"
			    "ODDLPRICE"
			    "ODDLYIELD"
			    "OFFSET"
			    "OPENINGBALANCEMONTH"
			    "OPENINGBALANCEQUARTER"
			    "OPENINGBALANCEYEAR"
			    "OR"
			    "ORDERBY"
			    "PARALLELPERIOD"
			    "PARTITIONBY"
			    "PATH"
			    "PATHCONTAINS"
			    "PATHITEM"
			    "PATHITEMREVERSE"
			    "PATHLENGTH"
			    "PDURATION"
			    "PERCENTILE.EXC"
			    "PERCENTILE.INC"
			    "PERCENTILEX.EXC"
			    "PERCENTILEX.INC"
			    "PERMUT"
			    "PI"
			    "PMT"
			    "POISSON.DIST"
			    "POWER"
			    "PPMT"
			    "PREVIOUS"
			    "PREVIOUSDAY"
			    "PREVIOUSMONTH"
			    "PREVIOUSQUARTER"
			    "PREVIOUSYEAR"
			    "PRICE"
			    "PRICEDISC"
			    "PRICEMAT"
			    "PRODUCT"
			    "PRODUCTX"
			    "PV"
			    "QUARTER"
			    "QUOTIENT"
			    "RADIANS"
			    "RAND"
			    "RANDBETWEEN"
			    "RANGE"
			    "RANK"
			    "RANK.EQ"
			    "RANKX"
			    "RATE"
			    "RECEIVED"
			    "RELATED"
			    "RELATEDTABLE"
			    "REMOVEFILTERS"
			    "REPLACE"
			    "REPT"
			    "RIGHT"
			    "ROLLUP"
			    "ROLLUPADDISSUBTOTAL"
			    "ROLLUPGROUP"
			    "ROLLUPISSUBTOTAL"
			    "ROUND"
			    "ROUNDDOWN"
			    "ROUNDUP"
			    "ROW"
			    "ROWNUMBER"
			    "RRI"
			    "RUNNINGSUM"
			    "SAMEPERIODLASTYEAR"
			    "SAMPLE"
			    "SAMPLEAXISWITHLOCALMINMAX"
			    "SAMPLECARTESIANPOINTSBYCOVER"
			    "SEARCH"
			    "SECOND"
			    "SELECTCOLUMNS"
			    "SELECTEDMEASURE"
			    "SELECTEDMEASUREFORMATSTRING"
			    "SELECTEDMEASURENAME"
			    "SELECTEDVALUE"
			    "SIGN"
			    "SIN"
			    "SINH"
			    "SLN"
			    "SQRT"
			    "SQRTPI"
			    "STARTOFMONTH"
			    "STARTOFQUARTER"
			    "STARTOFYEAR"
			    "STDEV.P"
			    "STDEV.S"
			    "STDEVX.P"
			    "STDEVX.S"
			    "SUBSTITUTE"
			    "SUBSTITUTEWITHINDEX"
			    "SUM"
			    "SUMMARIZE"
			    "SUMMARIZECOLUMNS"
			    "SUMX"
			    "SWITCH"
			    "SYD"
			    "T.DIST"
			    "T.DIST.2T"
			    "T.DIST.RT"
			    "T.INV"
			    "T.INV.2T"
			    "TAN"
			    "TANH"
			    "TBILLEQ"
			    "TBILLPRICE"
			    "TBILLYIELD"
			    "TIME"
			    "TIMEVALUE"
			    "TOCSV"
			    "TODAY"
			    "TOJSON"
			    "TOPN"
			    "TOPNPERLEVEL"
			    "TOPNSKIP"
			    "TOTALMTD"
			    "TOTALQTD"
			    "TOTALYTD"
			    "TREATAS"
			    "TRIM"
			    "TRUE"
			    "TRUNC"
			    "UNICHAR"
			    "UNICODE"
			    "UNION"
			    "UPPER"
			    "USERCULTURE"
			    "USERELATIONSHIP"
			    "USERNAME"
			    "USEROBJECTID"
			    "USERPRINCIPALNAME"
			    "UTCNOW"
			    "UTCTODAY"
			    "VALUE"
			    "VALUES"
			    "VAR.P"
			    "VAR.S"
			    "VARX.P"
			    "VARX.S"
			    "VDB"
			    "WEEKDAY"
			    "WEEKNUM"
			    "WINDOW"
			    "XIRR"
			    "XNPV"
			    "YEAR"
			    "YEARFRAC"
			    "YIELD"
			    "YIELDDISC"
			    "YIELDMAT"
                            ))

             ;; generate regex string for each category of keywords
             (x-keywords-regexp (regexp-opt x-keywords 'words))
					;(x-types-regexp (regexp-opt x-types 'words))
					;(x-constants-regexp (regexp-opt x-constants 'words))
					;(x-events-regexp (regexp-opt x-events 'words))
             (x-functions-regexp (regexp-opt x-functions 'symbols)))

        `(
					;(,x-types-regexp . font-lock-type-face)
					;(,x-constants-regexp . font-lock-constant-face)
					;(,x-events-regexp . font-lock-builtin-face)
          (,x-keywords-regexp . font-lock-keyword-face)
          (,x-functions-regexp . font-lock-function-name-face)
          ;; note: order above matters, because once colored, that part won't change.
          ;; in general, put longer words first
          )))

;;;###autoload
(define-derived-mode dax-mode c-mode "dax mode"
  "Major mode for editing DAX ( Language)…"

  ;; code for syntax highlighting
  (setq font-lock-defaults '(dax-font-lock-keywords nil t))
  (set (make-local-variable 'indent-line-function) #'indent-relative)
  )

;; add the mode to the `features' list
(provide 'dax-mode)

;;; dax-mode.el ends here
